
DEFINE_EXTLOG_TAG(SLOWQUERY)
DEFINE_EXTLOG_TAG(DBTOP)
DEFINE_EXTLOG_TAG(USERMAP)
DEFINE_EXTLOG_TAG(MONITOR)
DEFINE_EXTLOG_TAG(SERVICE)
DEFINE_EXTLOG_TAG(FREEZE)
DEFINE_EXTLOG_TAG(UNFREEZE)
DEFINE_EXTLOG_TAG(MYSQLCMD)
